export const ALLOWED_CATEGORY_IDS = [
  'real-world-assets-rwa',
  'infrastructure',
  'depin',
  'decentralized-finance-defi',
  'payment',
  'enterprise-solutions',
  'business-services',
  'energy',
  'supply-chain',
  'healthcare',
  'insurance',
  'legal',
  'identity',
  'storage',
  'oracle',
  'layer-2',
  'smart-contract-platform',
] as const;

export const CATEGORY_LABELS: Record<string, string> = {
  'real-world-assets-rwa': 'Real World Assets',
  infrastructure: 'Infrastructure',
  depin: 'DePIN',
  'decentralized-finance-defi': 'DeFi',
  payment: 'Payments',
  'enterprise-solutions': 'Enterprise',
  'business-services': 'Business Services',
  energy: 'Energy',
  'supply-chain': 'Supply Chain',
  healthcare: 'Healthcare',
  insurance: 'Insurance',
  legal: 'Legal',
  identity: 'Identity',
  storage: 'Storage',
  oracle: 'Oracle',
  'layer-2': 'Layer 2',
  'smart-contract-platform': 'Smart Contract Platform',
};
